model=FRB-X
name=HONOR MagicBook X14 Plus 2025
year=2025
platform=raptorlake
dgpu=none

origin=linux-hardware probe e706235ea5
status=probed
verified_kernel=unknown
verified_bios=1.02
verified_distro=unknown

dmi_vendor=HONOR
dmi_product=FRB-X
dmi_board=FRB-X-PCB
dmi_board_version=M1050
dmi_sku=unknown

touchscreen_hid=unknown
touchpad_hid=347d:7853
audio_ssid=1ee7:2074
fingerprint_usb=27c6:5f91
camera_usb=3277:0045
panel=lcd
backlight_max=unknown
ec_fan0=unknown
ec_fan1=unknown
battery_charge_presets=unknown

param_backlight_min=unknown
param_audio_fixup=unknown

fixes=
